argparse:
    label: "simple"
    eosurl: root://cmseos.fnal.gov/

    files: 
        default: input/DYToLL_M-50_TuneCP5_14TeV-pythia8.txt
        help: path to files or text file containing files
        nargs: +

    outfile: "dimuon_{branch}_{label}.root"

    branch: "gmtTkMuon"
    eta_min: 0 # abs_eta minimum
    eta_max: 2.4 # abs_eta maximum
    pt_min: 5.
    pt_max: 100.

    barrel_eta: 0.83
    endcap_eta: 1.24

    unscale_l1_muon_pt: True

    total: -1

# matched_delta_r: 0.1
muon_mass: 0.1

gen_tree:
    tree: genTree/L1GenTree

    variables:
        pt: "partPt"
        eta: "partEta"
        phi: "partPhi"

    selection:
        stat: "lambda t : t.partStat == 1"
        ptcut: "lambda t : (t.partPt > {pt_min})"
        etacut: "lambda t : (abs(t.partEta) < {eta_max})"
    
l1_tree: 
    tree: gmtTkMuonChecksTree/L1PhaseIITree

    variables:
        pt: "{branch}Pt"
        eta: "{branch}Eta"
        phi: "{branch}Phi"

    selection:
        ptcut: "lambda t : (t.{branch}Pt > {pt_min})"
        etacut: "lambda t : (abs(t.{branch}Eta) < {eta_max})"

        