argparse:
    label: "simple"

    file: "L1NtuplePhaseII_Step1"
    filepath: "/eos/uscms/store/user/ekoenig/trigger/"
    outfile: "effi_{file}_{label}.root"

    branch: "gmtTkMuon"
    eta_min: -2.4
    eta_max: 2.4
    pt_min: 2.
    pt_max: 100.

    barrel_eta: 0.83
    endcap_eta: 1.24

    total_events: -1

matched_delta_r: 0.1

gen_variables:
    pt: "partPt"
    eta: "partEta"
    phi: "partPhi"
    E: "partE"
    charge: "partCh"

gen_selection:
    stat: "lambda t : t.partStat == 1"
    ptcut: "lambda t : (t.partPt > {pt_min}) & (t.partPt < {pt_max})"
    etacut: "lambda t : (t.partEta > {eta_min}) & (t.partEta < {eta_max})"
    # barrelcut: "lambda t : ( np.abs(t.partEta) < 0.9)"
    # overlapcut: "lambda t : (np.abs(t.partEta) > 0.9) & (np.abs(t.partEta)<1.3"
    # endcapcut: "lambda t : np.abs(t.partEta) > 1.3"
    

l1_variables:
    pt: "{branch}Pt"
    eta: "{branch}Eta"
    phi: "{branch}Phi"
    # E: "{branch}E"
    charge: "{branch}Chg"
    # nstubs: "{branch}NStubs"

l1_selection:
    # nstubs>=2: "lambda t : t.{branch}NStubs >= 2"