
argparse:
    # To normalize to total rate at 200:
    # 2760.0*11246/1000 = 31038
    label: "EXAMPLE_SIMPLEEFFI"

    file: "DoubleMu_GMTIso_ID"
    filepath: "/eos/uscms/store/user/ekoenig/trigger/"
    outfile: "effi_example_{file}_{label}.root"

    branch: "gmtTkMuon"
    eta_range: [0, 2.4]
    pt_range: [2, 100]

    total: -1

matched_delta_r: 0.1

gen_select:
    - "{Stat} == 1"
    - "abs({Id}) == 13"
    - "abs({Eta}) > {eta_range[0]}"
    - "abs({Eta}) < {eta_range[1]}"
    - "{Pt} > {pt_range[0]}"
    - "{Pt} < {pt_range[1]}"

l1_matched_select:
#     - "{NStubs} >= 2"



